### ISSUE TITLE
Print CSS

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#22]
Basic Print CSS should be in place. 

* Hide whatever needs to be hidden (mainly navigation—Bootstrap is loaded so `.hidden-print` is possible but probably not need)
* Display any hidden Compass maps 
* on overview pages, show and linearize overview content

Something like this for links would be great:
```css
p a:after {
  content: " (" attr(href) ")";
  font-size: 80%;
}
```
And avoiding awkward page breaks:
```css
h1, h2, h3, h4, h5, h6, header { 
  page-break-after:avoid; 
  page-break-inside:avoid;
}
img { 
   page-break-inside:avoid; 
   page-break-after:avoid; 
}
blockquote, table, pre { 
  page-break-inside:avoid;
}
ul, ol, dl, footer  { 
  page-break-before:avoid; 
}
```
